version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=neuralapi
      - JWT_SECRET=my_random_secret_key
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5433:5432" # Изменён внешний порт на 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neuralapi
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
